pipeline {
	environment {	
registry = "785131266845.dkr.ecr.us-east-1.amazonaws.com/otel-demo"
registryCredential = 'AWSaccess'
dockerImage = ''
	}	
	
  agent any

    stages {
        stage('Build') {
            steps {
                sh """
                sudo mvn clean install -DskipTests
		"""
            }
        }
        stage('Test') {
            steps {
                sh """
                sudo mvn compile test"""
            }
        }
       stage('Sonar') {
            steps {
                sh """
                sudo mvn sonar:sonar
                """
            }
        }  
	stage('Building image') {
	    steps{
                script {
                dockerImage = docker.build registry + ":$BUILD_NUMBER"
                 }
             }
         }
	stage('Publish image') {
	    steps{
	      script {
	      docker.withRegistry( '', registryCredential ) {
	     dockerImage.push()
	 	  }
	       }
	    }
	}	    
	    
    }
}
